### PR TITLE
Create PVC object for docker-compose volumes

### LINKED ISSUE #150: Persistent Volumes
We should start thinking about proper volume implementation.

Kompose should create PersistentVolumeClaims and use those for pod volumes, instead of using EmptyDir.

Real persistent volumes might also solve `volumes_from` problem (#131)

### PR DESCRIPTION
**Pull request by surajssd**
Instead of creating emptydir, create PersistentVolumeClaim for docker-compose volumes by default

Fixes #150

### CODE REVIEW

**Comment by sebgoa** [comment]
it would be great to test this on minikube, to make sure we know that this is now supported.

**Comment by sebgoa** [comment]
thanks for including tests and fixtures.

LGTM

**Comment by surajssd** [comment]
@sebgoa The fixture I have added can be directly fed to a running k8s cluster or OpenShift cluster provided you have PV already available. I tried it on minikube and a single node OpenShift cluster, and the mounts work.

**Comment by surajssd** [comment]
I created PV using following artifact

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vol1
  labels:
    type: local
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/home/docker/data"
```

**Comment by ngtuna** [comment]
LGTM and tests are visible so this should be in 0.1.1 as well. Merging.

**Comment by ngtuna** [comment]
@surajssd there was a test run failed on this PR. I'm looking on it
https://travis-ci.org/skippbox/kompose/builds/165631060

**Comment by ngtuna** [comment]
Got it. 
```console
kompose -f /home/travis/gopath/src/github.com/skippbox/kompose/script/test/fixtures/volume-mounts/simple-vol-mounts/docker-compose.yml convert --stdout --dc
```
That should include the new born `--provider` flag to figure out OpenShift. I will send a separate PR for this.

**Pull request merged**
