### PR TITLE
fix param order in readme

### PR DESCRIPTION
**Pull request by sharpner**
tried the latest stable (mac os x) and I had to use ``` kompose convert docker-compose.yml```

### CODE REVIEW

**Comment by sebgoa** [comment]
thanks for reporting the issue. There is a `-f` missing in the readme that's for sure.

But the order is correct for HEAD.

I suspect you download the 0.1.0 release ?

We will put a 0.1.1 release up to avoid this. I will keep the PR open until we fix it. Hopefully today.

@ngtuna, can you upload a 0.1.1 release in github releases page.

**Comment by sharpner** [comment]
ah yeah I downloaded 0.1.0. Thanks for the fast response :)

**Comment by ngtuna** [comment]
@sharpner 0.1.1 is made for you https://github.com/skippbox/kompose/releases/tag/v0.1.1

**Comment by sharpner** [comment]
perfect thx

**Pull request closed without merging**
