### PR TITLE
Use libcompose project.Context{} instead of docker.Context{}

### LINKED ISSUE #134: Should we use libcompose project.Context{} instead of docker.Context{}?
I may miss something, but I don't understand why we will need to use `&docker.Context{}` when we load compose file in [loader pkg](https://github.com/skippbox/kompose/blob/master/pkg/loader/compose/compose.go#L95)
Isn't [`project.Context{}`](https://github.com/docker/libcompose/blob/master/project/context.go#L21) sufficient? The difference are:
```go
	ClientFactory client.Factory
	ConfigDir     string
	ConfigFile    *configfile.ConfigFile
	AuthLookup    auth.Lookup
```

### PR DESCRIPTION
**Pull request by ngtuna**
Fix #134

### CODE REVIEW

**Comment by ngtuna** [comment]
Rebased

**Comment by ngtuna** [comment]
Can someone check this tiny but helpful change? @kadel @runseb

**Comment by kadel** [comment]
I didn't  checked what are  differences between `project.Context` and `docker.Context`.
But if it compiles and works why not ;-)
LGTM

**Comment by ngtuna** [comment]
@kadel Yeah, In #134 Weitenghuang explained the difference.
```
We don't need to use libcompose's docker pkg context, if kompose is not meant to build a docker client.
```
`project.Context` is just enough for kompose I believe.

**Pull request merged**
