### PR TITLE
Update .dsb references to .dab

### PR DESCRIPTION
**Pull request by cdrage**
Updates the new file extension for distributed application bundles.

### CODE REVIEW

**Comment by kadel** [comment]
thank you :+1: 
if you are in it, can you also rename dsb files in examples? :wink:

**Comment by cdrage** [comment]
@kadel i already did in https://github.com/skippbox/kompose/pull/183 :) needs to just be murged

**Comment by kadel** [comment]
ahh, sorry,  I missed that

**Comment by sebgoa** [comment]
+1

merging.

**Pull request merged**
