### PR TITLE
Create service function in kubernetes utils

### PR DESCRIPTION
**Pull request by surajssd**
This function can be used in both openshift and kubernetes and all the logic of creating service can be kept in this function.

### CODE REVIEW

**Comment by surajssd** [comment]
Should go in, after https://github.com/skippbox/kompose/pull/107 is merged and rebased on https://github.com/skippbox/kompose/pull/107

**Comment by janetkuo** [comment]
This needs rebase on #106; please rename sc to svc (official short name for service)

**Comment by surajssd** [comment]
Rebased on #106

**Comment by surajssd** [comment]
ping @ngtuna

**Comment by ngtuna** [comment]
Yeah LGTM. I thought @janetkuo did add `lgtm` label.

**Comment by surajssd** [comment]
@ngtuna np, Thanks for reviewing :+1: Merging.

**Pull request merged**
