### PR TITLE
Functional Testing for kompose cmdline

### PR DESCRIPTION
**Pull request by surajssd**
Shell scripts to test k8s and os conversion

### CODE REVIEW

**Comment by ngtuna** [comment]
Super! Thanks @surajssd for the patch.

**Comment by ngtuna** [comment]
@surajssd I ran the test by executing `test/cmd/tests.sh` and got fails look similar this one:

```console
===> Starting test <===
convert::expect_success_and_warning: Running: 'kompose convert --stdout -f /home/tuna/workspace/gocode-kompose/src/github.com/skippbox/kompose/test/fixtures/etherpad/docker-compose.yml' expected_output: '/home/tuna/workspace/gocode-kompose/src/github.com/skippbox/kompose/test/fixtures/etherpad/output-k8s.json' expected_warning: 'Unsupported key depends_on - ignoring'
jq: Unknown option --argfile
Use jq --help for help with command-line options,
or see the jq documentation at http://stedolan.github.com/jq
FAIL: converted output does not match
```

Also note: `jq` is prerequisite. We should mention it in README.

**Comment by ngtuna** [comment]
Also, could you move test/ to script's subfolder ? Thanks.

**Comment by surajssd** [comment]
@ngtuna I am using `jq - commandline JSON processor [version 1.5]` what version are you using?

**Comment by ngtuna** [comment]
@surajssd mine is `jq 1.3` (latest on ubuntu 14.04). So it needs `jq` 1.5. If you mention this requirement in `test/README.md` then we should be good.

**Comment by surajssd** [comment]
I have moved this under `script` directory.

**Pull request merged**
