### PR TITLE
Run tests on travis-ci

### PR DESCRIPTION
**Pull request by kadel**
related to #34 

-  run commandline tests and unit test on travis-ci (`make test-unit` and `make test-cmd`)
- `make binary` builds only binary for current arch platform where script is running (no cross compiling)
- added `make binary-cross` same as former `make binary` (cross compile for mac/linux/win 386/amd65)

command line test is failing because of #88 and #92

### CODE REVIEW

**Comment by runseb** [comment]
+1, we just need to check the tests

**Comment by ngtuna** [comment]
👍 @kadel. I will check this after dinner.

**Comment by ngtuna** [comment]
@kadel I tested on ubuntu 16.04.
- `make binary-cross` doesn't output binaries.
- `make binary-cross` and `make binary` doesn't print anything. It would be better to print output then user can see what's happening like this:
```console
$ make binary
./script/make.sh binary
---> Making bundle: binary (in .)

Number of parallel builds: 1

-->   windows/amd64: github.com/skippbox/kompose/cli/main
-->       linux/386: github.com/skippbox/kompose/cli/main
-->      darwin/386: github.com/skippbox/kompose/cli/main
-->    darwin/amd64: github.com/skippbox/kompose/cli/main
-->     linux/amd64: github.com/skippbox/kompose/cli/main
-->     windows/386: github.com/skippbox/kompose/cli/main
```

**Comment by kadel** [comment]
ahh my bad :smile: `make binary-cross` points to `makes.sh binary`, to it just builds for current platform :-) I'll fix that and I'll also add info about successful build for `make binary`.

Thank you for noticing that.

**Pull request merged**
