### PR TITLE
Refactor how we update controllers

### PR DESCRIPTION
**Pull request by janetkuo**
Refactor so that we don't need to copy & paste code for updating each controller.

### CODE REVIEW

**Comment by runseb** [comment]
Not sure what happened, it seems I added a label while I was sleeping, weird.

@janetkuo is it ready for review+merge or are you still working on it ?

**Comment by ngtuna** [comment]
Thanks @janetkuo . Nice to see a generic update function for controllers. Shall we keep discussing to optimize `convert` function in order to look better ? It's simply too long.

**Comment by janetkuo** [comment]
Yes it's ready for review. Agree with Tuna, I'd love to optimize convert as
well.

**Comment by ngtuna** [comment]
@janetkuo @runseb I checked out the PR. It looks good to me.

**Pull request merged**
