### PR TITLE
make --file as global flag

### PR DESCRIPTION
**Pull request by ngtuna**
Fix https://github.com/skippbox/kompose/issues/138

/cc @runseb

### CODE REVIEW

**Comment by janetkuo** [comment]
Looks like `-f` now needs to come right after `kompose` and before subcommands? We need to update all related docs as well (since we used `kompose convert -f` in our docs)

**Comment by ngtuna** [comment]
@janetkuo Right. Will add a follow up commit.

**Comment by runseb** [comment]
LGTM let's wait for @janetkuo to reply

**Comment by kadel** [comment]
@ngtuna can you please rebase this to current master?
There are two new tests as part of https://github.com/skippbox/kompose/pull/127, they have to be updated also.

**Comment by ngtuna** [comment]
@kadel Done

**Comment by kadel** [comment]
thank you. lgtm

**Comment by ngtuna** [comment]
So I'm gonna merge it now.

**Pull request merged**
