### PR TITLE
Support for environment variables substitution

### LINKED ISSUE #56: Environment Variable substitution not working
I am using following `docker-compose.yml` file
```yaml
$ cat docker-compose.yml 
version: "2"

services:
  mariadb:
    image: centos/mariadb
    ports:
      - "$DB_PORT"
    environment:
      MYSQL_ROOT_PASSWORD: $ROOT_PASS
      MYSQL_DATABASE: $DB_NAME
      MYSQL_PASSWORD: $DB_PASS
      MYSQL_USER: $DB_USER

  etherpad:
    image: centos/etherpad
    ports:
      - "80:9001"
    depends_on:
      - mariadb
    environment:
      DB_HOST: $DB_HOST
      DB_DBID: $DB_NAME
      DB_PASS: $DB_PASS
      DB_PORT: $DB_PORT
      DB_USER: $DB_USER
```

and following envs

```bash
$ cat envs 
DB_HOST=mariadb
ROOT_PASS=etherpad
DB_NAME=etherpad
DB_PASS=etherpad
DB_USER=etherpad
DB_PORT=3306
```

error
```
$ export $(cat envs)
$ ./kompose convert -o output
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x64e144]

goroutine 1 [running]:
panic(0x11ef080, 0xc820010140)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/skippbox/kompose/vendor/github.com/docker/libcompose/config.Interpolate.func1(0xc8204acc88, 0x7, 0x0, 0x0)
	/home/vagrant/work/src/github.com/skippbox/kompose/vendor/github.com/docker/libcompose/config/interpolation.go:145 +0x84
github.com/skippbox/kompose/vendor/github.com/docker/libcompose/config.parseVariable(0xc8204ac790, 0x8, 0x8, 0xc82015fbe8, 0x0, 0x0, 0x0, 0xc8204ba150)
	/home/vagrant/work/src/github.com/skippbox/kompose/vendor/github.com/docker/libcompose/config/interpolation.go:36 +0x120
github.com/skippbox/kompose/vendor/github.com/docker/libcompose/config.parseInterpolationExpression(0xc8204ac790, 0x8, 0x1, 0xc82015fbe8, 0x0, 0x0, 0xc82015f7a8, 0x4127d8)
	/home/vagrant/work/src/github.com/skippbox/kompose/vendor/github.com/docker/libcompose/config/interpolation.go:74 +0x10f
github.com/skippbox/kompose/vendor/github.com/docker/libcompose/config.parseLine(0xc8204ac790, 0x8, 0xc82015fbe8, 0x0, 0x0, 0x412672)
	/home/vagrant/work/src/github.com/skippbox/kompose/vendor/github.com/docker/libcompose/config/interpolation.go:90 +0xbf
github.com/skippbox/kompose/vendor/github.com/docker/libcompose/config.parseConfig(0xc8204ac718, 0x5, 0xc8204ac6f0, 0x7, 0xc82015f990, 0xc82015fbe8, 0x0, 0x0)
	/home/vagrant/work/src/github.com/skippbox/kompose/vendor/github.com/docker/libcompose/config/interpolation.go:110 +0x532
github.com/skippbox/kompose/vendor/github.com/docker/libcompose/config.parseConfig(0xc8204ac718, 0x5, 0xc8204ac6f0, 0x7, 0xc82015fb68, 0xc82015fbe8, 0x0, 0x0)
	/home/vagrant/work/src/github.com/skippbox/kompose/vendor/github.com/docker/libcompose/config/interpolation.go:117 +0x1d3
github.com/skippbox/kompose/vendor/github.com/docker/libcompose/config.Interpolate(0x0, 0x0, 0xc82015fd38, 0x0, 0x0)
	/home/vagrant/work/src/github.com/skippbox/kompose/vendor/github.com/docker/libcompose/config/interpolation.go:144 +0x1f3
github.com/skippbox/kompose/vendor/github.com/docker/libcompose/config.MergeServicesV2(0xc8204638c0, 0x0, 0x0, 0x0, 0x0, 0xc820463880, 0x12, 0xc82049c000, 0x1d9, 0x3d9, ...)
	/home/vagrant/work/src/github.com/skippbox/kompose/vendor/github.com/docker/libcompose/config/merge_v2.go:22 +0x12a
github.com/skippbox/kompose/vendor/github.com/docker/libcompose/config.Merge(0xc8204638c0, 0x0, 0x0, 0x0, 0x0, 0xc820463880, 0x12, 0xc82049c000, 0x1d9, 0x3d9, ...)
	/home/vagrant/work/src/github.com/skippbox/kompose/vendor/github.com/docker/libcompose/config/merge.go:40 +0x24c
github.com/skippbox/kompose/vendor/github.com/docker/libcompose/project.(*Project).load(0xc8204651e0, 0xc820463880, 0x12, 0xc82049c000, 0x1d9, 0x3d9, 0x0, 0x0)
	/home/vagrant/work/src/github.com/skippbox/kompose/vendor/github.com/docker/libcompose/project/project.go:178 +0xe5
github.com/skippbox/kompose/vendor/github.com/docker/libcompose/project.(*Project).Parse(0xc8204651e0, 0x0, 0x0)
	/home/vagrant/work/src/github.com/skippbox/kompose/vendor/github.com/docker/libcompose/project/project.go:86 +0x335
github.com/skippbox/kompose/cli/app.loadComposeFile(0xc820463880, 0x12, 0xc820347180, 0x0)
	/home/vagrant/work/src/github.com/skippbox/kompose/cli/app/app.go:733 +0x1b6
github.com/skippbox/kompose/cli/app.Convert(0xc820347180)
	/home/vagrant/work/src/github.com/skippbox/kompose/cli/app/app.go:1028 +0x4b9
github.com/skippbox/kompose/cli/command.ConvertCommand.func1(0xc820347180)
	/home/vagrant/work/src/github.com/skippbox/kompose/cli/command/command.go:30 +0x21
github.com/skippbox/kompose/vendor/github.com/urfave/cli.Command.Run(0x13eb378, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x159d920, 0x30, 0x0, ...)
	/home/vagrant/work/src/github.com/skippbox/kompose/vendor/github.com/urfave/cli/command.go:179 +0x1399
github.com/skippbox/kompose/vendor/github.com/urfave/cli.(*App).Run(0xc82048ab00, 0xc82000a940, 0x4, 0x4, 0x0, 0x0)
	/home/vagrant/work/src/github.com/skippbox/kompose/vendor/github.com/urfave/cli/app.go:196 +0x137c
main.main()
	/home/vagrant/work/src/github.com/skippbox/kompose/cli/main/main.go:46 +0x5fe
```

version

```bash
$ ./kompose -v
kompose version 0.0.1-alpha (HEAD)
```

### PR DESCRIPTION
**Pull request by surajssd**
Now user can put environment variables in docker-compose file and it will be read by kompose from environment

Fixes #56

### CODE REVIEW

**Comment by surajssd** [comment]
The code in this PR is from https://github.com/docker/libcompose/blob/master/docker/project.go#L25


So I needed some discussion around this PR, so I checked the code in kompose [here](https://github.com/skippbox/kompose/blob/master/cli/app/app.go#L738), it is similar to code in libcompose [here](https://github.com/docker/libcompose/blob/master/docker/project.go#L25). So I was hoping we can use the function [`NewProject`](https://github.com/docker/libcompose/blob/master/docker/project.go#L25) from libcompose which is under docker package not under [project package](https://github.com/docker/libcompose/blob/master/project/project.go#L43).

So the downside of using `docker` package's `NewProject` is it returns `project.APIProject` and I would like to have a method in `project.APIProject` that returns internal data structure of type `*Project` and we don't need to repeat the code. So I will be working with libcompose to get this done. If that works out this PR will change!

**Comment by ngtuna** [comment]
@surajssd I see you are changing libcompose code in `/vendor`. Is it possible to just work on kompose code base and keep libcompose as a dependency ?

**Comment by surajssd** [comment]
@ngtuna I did `godep save` to get latest code from libcompose. Is it not the right way to do it?

**Comment by ngtuna** [comment]
@surajssd Ah okay you changed libcompose revision to HEAD. OK let me check it.

**Comment by surajssd** [comment]
@ngtuna @kadel How can I convert a [`APIProject`](https://github.com/docker/libcompose/blob/master/project/interface.go#L12) interface object type to [`Project`](https://github.com/docker/libcompose/blob/master/project/project.go#L23) type? Is there a way to do it?

**Comment by ngtuna** [comment]
@surajssd  The reason I didn't use [NewProject](https://github.com/docker/libcompose/blob/master/docker/project.go#L25) function because I don't want kompose to be constrained by libcompose. Basically we only need its parsing function in order to parse docker compose file into komposeObject, nothing more. Otherwise, we have to follow libcompose's constraints such as it's required to have a `docker-compose.yml` file handy at the same folder.

Did you check whether your changes in cli/app/app.go still works with the current libcompose revision at HEAD master? If yes then I suggest to keep the vendoring stable and just apply your changes in app.go. I can't check it now but will do tomorrow morning.

**Comment by surajssd** [comment]
@ngtuna I checked with the vendored libcompose available I am not able to build, because I need https://github.com/skippbox/kompose/pull/67/files#diff-41d801ef80f1858d5e8e9695667e4dafR749 and it is not in the vendored `libcompose`

**Comment by ngtuna** [comment]
Checked! Thanks @surajssd . Please go ahead to merge upstream.

**Comment by surajssd** [comment]
@ngtuna thank you :)

**Pull request merged**
