### PR TITLE
Update tests output files

### PR DESCRIPTION
**Pull request by surajssd**
With the recent changes in the output format as List, updated tests as well so they validate on the new format of output.

### CODE REVIEW

**Comment by janetkuo** [comment]
Which `kompose` binary is the test using? Should it rebuild the binary before the test?

**Comment by surajssd** [comment]
Yes binary was rebuilt before test and it is put in system's `PATH`.

**Comment by ngtuna** [comment]
Hey @surajssd , just a quick check (I am missing something, sorry that my head is struggling...). Did we cover the `docker-compose-no-image.yml` case in master branch? I got this fail (only this):

```console
===> Starting test <===
convert::expect_failure: Running: 'kompose convert --stdout -f /home/travis/gopath/src/github.com/skippbox/kompose/script/test/fixtures/etherpad/docker-compose-no-image.yml'
FAIL: no error output, returned exit status 0
```

**Comment by ngtuna** [comment]
Ah I found it. Still open https://github.com/skippbox/kompose/issues/80. So how can we bypass this case in the current travis-ci test ? Or just ignore it and merge like @kadel did yesterday?

**Comment by surajssd** [comment]
@ngtuna yes i think we need to ignore it for now or if you suggest I can comment the test for now and then uncomment it when it gets fixed?

**Comment by ngtuna** [comment]
@surajssd yes please do.

**Comment by surajssd** [comment]
@ngtuna thanks :)

**Pull request merged**
